name: Deploy docker to AWS

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PK }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/2024-1B-T02-EC10-G05/src/docker
            git checkout dev
            git pull
            echo "Stopping and removing old containers"
            docker compose -f docker-compose.prod.yaml down
            echo "Building and starting containers"
            docker compose -f docker-compose.prod.yaml up -d --build

            COMPOSE_UP_EXIT_CODE=$?
            if [ $COMPOSE_UP_EXIT_CODE -ne 0 ]; then
                echo "docker compose up failed"
                exit 1
            fi

            sleep 10  # Aguardar alguns segundos para garantir que os serviÃ§os estejam iniciados
            # Verificar o status dos containers
            STATUS=$(docker compose ps | grep -E "Exit|Restarting" || true)
            if [ -n "$STATUS" ]; then
                echo "One or more services are not running correctly"
                exit 1
            fi
            # Verificar logs dos containers para mensagens de erro (opcional)
            LOGS=$(docker compose logs 2>&1 | grep -i "error" || true)
            if [ -n "$LOGS" ]; then
                echo "Error found in container logs"
                echo "$LOGS"
                exit 1
            fi
          EOF
